<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.5 setup script
 * Date: Sun, 16 Aug 2020 16:53:50 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: 127.0.0.1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '/tmp/mysql.sock';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '1';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'u/ZP;wuvCyTSQ$[,7KtlcKZ:_fKG.DsP';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>